[package]
name = "compiler-frontend-generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bit-set = "0.6.0"
derive-where = "1.2.7"
serde = "1.0.203"
serde_derive = "1.0.203"
